[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0760
chown=root:frappe

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[group:frappe]
programs=frappe-web,frappe-socketio,frappe-worker-long,frappe-scheduler


[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql --datadir=/var/lib/mysql --skip-grant-tables=false
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --port 6379 --save ""
autostart=true
autorestart=true
priority=10
user=redis
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frappe-web]
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=0.0.0.0:8000 --threads=4 --workers=2 --worker-class=gthread --worker-tmp-dir=/dev/shm --timeout=120 --reload --reload-extra-file /home/frappe/frappe-bench/sites/apps.txt frappe.app:application
directory=/home/frappe/frappe-bench/sites
autostart=true
autorestart=true
priority=30
user=frappe
environment=HOME="/home/frappe",USER="frappe"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frappe-socketio]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
directory=/home/frappe/frappe-bench/sites
autostart=true
autorestart=true
priority=30
user=frappe
environment=HOME="/home/frappe",USER="frappe"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frappe-worker-long]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue long,default,short
directory=/home/frappe/frappe-bench/sites
autostart=true
autorestart=true
priority=30
user=frappe
environment=HOME="/home/frappe",USER="frappe"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frappe-worker-short]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue short,default
directory=/home/frappe/frappe-bench/sites
autostart=true
autorestart=true
priority=30
user=frappe
environment=HOME="/home/frappe",USER="frappe"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frappe-scheduler]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe schedule
directory=/home/frappe/frappe-bench/sites
autostart=true
autorestart=true
priority=30
user=frappe
environment=HOME="/home/frappe",USER="frappe"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
